### ISSUE TITLE
io_uring: sqthread_poll with hipri (submisson polling with completion polling)

### ISSUE THREAD

**Issue by mmisono** [ZebinRen/Performance-Characterization-Storage-Stacks#3]
Hi,

I have a qeustion -- [the paper](https://atlarge-research.com/pdfs/2023-cheops-iostack.pdf) says

> This mode is referred to as submission polling (iou-s, with the hipri flag).

but it seems `iou-s` configuration only uses `sqthread_poll` flag:  https://github.com/ZebinRen/Performance-Characterization-Storage-Stacks/blob/master/3-c-work_breakdown_qd1/iou_s.conf#L14

Does fio set `hipri` automatically when enabling `sqthread_poll`?

**Comment by ZebinRen** [comment]
Hi, `hipri` is not automatically enabled when `sqthread_poll` is set. The flag should be `sqthread_poll` instead of `hipri`.

**Comment by mmisono** [comment]
Thanks for the clarification.
